###
GET http://localhost:3000/books

###
GET http://localhost:3000/books/hola5

###
PATCH  http://localhost:3000/books/a

### 
POST http://localhost:3000/books
Content-Type: application/json

{
    "title": "Los patos de goma",
    "pages": 1200,
    "genre": "Hola",
    "cover": "http://nanjsla.com",
    "synopsis": "Una aventura épica en un mundo de fantasía llamado la Tierra Media.",
    "year": 1980,
    "ISBN": "9788781-9901"
}

###
DELETE http://localhost:3000/books/los-patos-de-goma
