###
GET http://localhost:3000/books

###
GET http://localhost:3000/cart

###
GET http://localhost:3000/books/el-señor-de-los-anillos

###
GET http://localhost:3000/books/el-señor-del-anillos

### 
GET http://localhost:3000/books?genre=Fantasía

### 
GET http://localhost:3000/books?genre=fantasía

###
PATCH  http://localhost:3000/books/el-señor-de-los-anillos