###
GET http://localhost:3000/books

###
GET http://localhost:3000/books/el-señor de los anillos

###
PATCH  http://localhost:3000/books/el-señor de los anillos

### 
POST  http://localhost:3000/books
Content-Type: application/json

{
    "title": "HOLA3",
    "pages": 1200,
    "genre": "Hola",
    "cover": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566425108i/33.jpg",
    "synopsis": "Una aventura épica en un mundo de fantasía llamado la Tierra Media.",
    "year": 1980,
    "ISBN": "978-0618640158",
    "author": {
        "name": "J.R.R. Tolkien",
        "otherBooks": [
            "El Hobbit",
            "El Silmarillion"
        ]
    }
}
