###
GET http://localhost:3000/book?pages=1000&?genre=1

###
POST http://localhost:3000/book
Content-Type: application/json

{
    "books": 
    [
        {
            "title": "El Señor de los Anillos",
            "pages": 1200,
            "genre": 1,
            "cover": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566425108i/33.jpg",
            "synopsis": "Una aventura épica en un mundo de fantasía llamado la Tierra Media.",
            "year": 1954,
            "ISBN": "978-0618640157"
        }
    ]
}

###
DELETE  http://localhost:3000/book/el-señor-de-los-anillos
